package com.billionsphere.api

class RESTURLS {
    companion object {
        const val refresh = "refresh"
        const val login = "login"
        const val register = "register"
        const val forgotPassword = "forgotPassword"
        const val verifyOtp = "verifyOtp"
        const val resetPassword = "resetPassword"
        const val resendOtp = "resendOtp"
        const val approvalStatus = "approvalStatus"
        const val logout = "logout"
        const val getUserWorkStatus = "getUserWorkStatus"
        const val digitalVisitingCard = "digitalVisitingCard"
        const val getServicesLists = "getServicesLists"
        const val getWorkNavLinks = "getWorkNavLinks"
        const val getCustomerWorkOrderDetails = "getCustomerWorkOrderDetails"
        const val getCustomerInvoiceDetails = "getCustomerInvoiceDetails"
        const val uploadPaymentDoc = "uploadPaymentDoc"
        const val getUploadPaymentDocuments = "getUploadPaymentDocuments"
        const val deletePaymentDoc = "deletePaymentDoc"
        const val getPaymentApprovedList = "getPaymentApprovedList"
        const val getDocumentSection = "getDocumentSection"
        const val getComplianceCategory = "getComplianceCategory"
        const val getComplianceRequirement = "getComplianceRequirement"
        const val getWorkSteps = "getWorkSteps"
        const val getDeliveryDocuments = "getDeliveryDocuments"
        const val getConversationDocuments = "getConversationDocuments"
        const val sendMessage = "sendMessage"
        const val storeDocumentSection = "storeDocumentSection"
        const val getMyProfileDetails = "getMyProfileDetails"
        const val getCustomerGroupUsers = "getCustomerGroupUsers"
        const val switchAccount = "switchAccount"
        const val getRoleSwitchAccount = "getRoleSwitchAccount"
        const val getYoutubeLinks = "getYoutubeLinks"
        const val changePassword = "changePassword"
        const val deleteAccount = "deleteAccount"
        const val getContactList = "getContactList"
    }

}